[package]
name = "hackpng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"
clap = {version = "4.3.8", features = ["derive"]}
colored = "2.0.0"
